name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Install minification tools
        run: npm install -g terser css-minifier html-minifier json-minify
      - name: Build
        run: CI=false npm run build
      - name: Minify JavaScript
        run: find build -type f -name '*.js' -exec terser {} -c -m -o {} \;
      - name: Minify CSS
        run: find build -type f -name '*.css' -exec css-minifier -i {} -o {} \;
      - name: Minify HTML
        run: find build -type f -name '*.html' -exec html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true -o {} {} \;
      - name: Minify JSON
        run: find build -type f -name '*.json' -exec sh -c 'json-minify {} > {}.min && mv {}.min {}' \;
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./build
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
